# Minimal builtins stubs to unblock Pyright/Pylance name resolution.

class object: ...

class type: ...

class BaseException(object): ...
class Exception(BaseException): ...
class RuntimeError(Exception): ...
class ValueError(Exception): ...
class FileNotFoundError(Exception): ...

class NoneType(object): ...
None: NoneType

class bool(int): ...
True: bool
False: bool

class str(object): ...
class int(object): ...
class float(object): ...

class dict(object): ...
class list(object): ...
class tuple(object): ...

def getattr(obj: object, name: str, default: object = ...) -> object: ...
def isinstance(obj: object, class_or_tuple: object) -> bool: ...
def len(obj: object) -> int: ...
def sum(iterable: object, start: object = ...) -> object: ...
def range(__stop: int) -> object: ...
def max(__iterable: object, *args: object) -> object: ...
