# Minimal pathlib stubs

from builtins import object, str

class Path(object):
    def __init__(self, *args: object) -> None: ...
    def resolve(self) -> "Path": ...
    @property
    def parents(self) -> object: ...
    def __truediv__(self, other: object) -> "Path": ...
