# Minimal typing stubs to unblock imports like: from typing import Any, Dict, List, Optional, Tuple

from builtins import object

Any = object

class Dict(object): ...
class List(object): ...
class Tuple(object): ...
class Optional(object): ...
